// Static exercise prescription rendered into the four workout containers.
const workoutPlan={
 seg:[['seg-hip','Hip Thrust','Máquina ou barra','3×8–12','90–120s'],['seg-leg','Leg Press 45°','Amplitude controlada','3×10–12','90s'],['seg-bulg','Agachamento búlgaro','Com apoio se necessário','2×10–12/cada','90s'],['seg-ext','Cadeira extensora','','2×12–15','60–75s'],['seg-abd','Abdutora','','2×15–20','60s'],['seg-pant','Panturrilha em pé/máquina','','2×12–15','60s']],
 qua:[['qua-pux','Puxada frontal','Pegada confortável','3×8–12','75–90s'],['qua-rem','Remada sentada','','3×8–12','75–90s'],['qua-des','Desenvolvimento de ombros','Máquina ou halteres','2×8–12','75s'],['qua-lat','Elevação lateral','','3×12–15','60s'],['qua-chest','Chest press','','2×10–12','75s'],['qua-bic','Rosca bíceps','','2×10–15','60s'],['qua-tri','Tríceps na polia','','2×10–15','60s']],
 sex:[['sex-rdl','Levantamento romeno','Halteres ou barra; coluna neutra','3×8–10','90–120s'],['sex-hip','Hip Thrust','','3×10–12','90–120s'],['sex-flex','Mesa/cadeira flexora','','3×10–15','75s'],['sex-step','Step-up ou passada reversa','','2×10–12/cada','90s'],['sex-abd','Abdutora','','2×15–20','60s'],['sex-pant','Panturrilha sentada/máquina','','2×12–15','60s']],
 dom:[['dom-pux','Puxada neutra','','3×8–12','75–90s'],['dom-rem','Remada unilateral','','2×10–12/cada','75s'],['dom-chest','Chest press','','2×10–12','75s'],['dom-des','Desenvolvimento de ombros','','2×8–12','75s'],['dom-lat','Elevação lateral','','3×12–15','60s'],['dom-post','Crucifixo invertido','Deltoide posterior','2×12–15','60s'],['dom-arm','Bíceps + tríceps','1 exercício de cada','2×10–15','60s']]
};
function seedExerciseRows(){Object.entries(workoutPlan).forEach(([day,items])=>{const root=document.getElementById('body-'+day);if(!root||root.children.length)return;root.innerHTML=items.map(([key,name,note,range,rest])=>`<div class="exercise" data-ex="${key}" data-range="${range}"><div class="name">${name}${note?`<small>${note}</small>`:''}</div><div class="data">${range}</div><div class="data rest">${rest}</div><input class="load-input" inputmode="decimal" placeholder="kg" data-load="${key}"><input class="reps-input" inputmode="numeric" placeholder="reps" data-reps="${key}"><button class="ex-check" data-key="${key}">✓</button><div class="exercise-sub"><span class="progress-hint" id="hint-${key}">Registre carga + repetições</span></div><div class="history-box" id="hist-${key}"></div></div>`).join('')})}
seedExerciseRows();
