// FORJA MUSCLE v3.0
const dayTargets={strength:{label:'Dia de musculação',kcal:2200,p:135,c:290,f:55,detail:'Mais carboidrato para sustentar treino e recuperação.'},cardio:{label:'Dia de cardio',kcal:2100,p:135,c:260,f:60,detail:'Energia intermediária com proteína preservada.'},rest:{label:'Dia de descanso',kcal:2000,p:135,c:225,f:62,detail:'Proteína estável e carboidrato um pouco menor.'}};
function autoDayType(){const d=selectedDate.getDay();if(isMuscleDay(d))return 'strength';if([2,6].includes(d))return 'cardio';return 'rest'}
function activeDayType(){const m=store.get('nutrition.dayType','auto');return m==='auto'?autoDayType():m}
function setManualDayType(t){store.set('nutrition.dayType',t);renderDayTargets()}
function renderDayTargets(){const a=activeDayType(),t=dayTargets[a],m=store.get('nutrition.dayType','auto');dayTypeTitle.textContent=t.label;dayTypeDetail.textContent=t.detail;dtKcal.textContent=t.kcal.toLocaleString('pt-BR')+' kcal';dtProtein.textContent=t.p+' g';dtCarb.textContent=t.c+' g';dtFat.textContent=t.f+' g';document.querySelectorAll('.day-type-switch button').forEach(b=>b.classList.toggle('active',b.dataset.dt===m));const x=selectedDayMacrosWithExtras(),set=(id,v,u)=>{const e=document.getElementById(id);e.textContent=(v>0?'+':'')+Math.round(v)+' '+u;e.className=v>=0?'good':'warn'};set('remainingKcal',t.kcal-x.kcal,'kcal');set('remainingProtein',t.p-x.p,'g');set('remainingCarb',t.c-x.c,'g');set('remainingFat',t.f-x.f,'g')}
function customFoods(){return store.get('customFoods',[])}
function saveCustomFood(){const name=cfName.value.trim(),serving=cfServing.value.trim();if(!name){toast('Informe o nome do alimento');return}const arr=customFoods();arr.push({id:Date.now(),name,serving,kcal:num(cfKcal.value)||0,p:num(cfProtein.value)||0,c:num(cfCarb.value)||0,f:num(cfFat.value)||0});store.set('customFoods',arr);cfName.value=cfServing.value=cfKcal.value=cfProtein.value=cfCarb.value=cfFat.value='';renderCustomFoods();renderDayTargets();toast('Alimento cadastrado')}
function customFoodExtrasForDay(){return store.get(dk('customExtras'),[])}
function toggleCustomExtra(id){let arr=customFoodExtrasForDay();if(arr.includes(id))arr=arr.filter(x=>x!==id);else arr.push(id);store.set(dk('customExtras'),arr);renderCustomFoods();renderDayTargets();renderSmartMacros()}
function deleteCustomFood(id){store.set('customFoods',customFoods().filter(x=>x.id!==id));store.set(dk('customExtras'),customFoodExtrasForDay().filter(x=>x!==id));renderCustomFoods();renderDayTargets();renderSmartMacros()}
function renderCustomFoods(){const foods=customFoods(),extras=customFoodExtrasForDay();customFoodList.innerHTML=foods.length?foods.map(x=>`<div class="custom-food-row"><b>${escapeAttr(x.name)}</b><span>${escapeAttr(x.serving||'1 porção')}</span><span>${x.kcal} kcal</span><span>${x.p}P</span><span>${x.c}C • ${x.f}G</span><button class="${extras.includes(x.id)?'added':''}" onclick="toggleCustomExtra(${x.id})">${extras.includes(x.id)?'No dia':'Adicionar hoje'}</button><button onclick="deleteCustomFood(${x.id})">Excluir</button></div>`).join(''):'<div class="empty-state">Nenhum alimento próprio cadastrado.</div>'}
function selectedDayMacrosWithExtras(){const base=selectedDayMacros(),ids=customFoodExtrasForDay(),foods=customFoods().filter(x=>ids.includes(x.id));return foods.reduce((a,x)=>({kcal:a.kcal+x.kcal,p:a.p+x.p,c:a.c+x.c,f:a.f+x.f}),base)}
const originalRenderSmartMacros=renderSmartMacros;renderSmartMacros=function(){const x=selectedDayMacrosWithExtras();smartKcal.textContent=Math.round(x.kcal).toLocaleString('pt-BR')+' kcal';smartProtein.textContent=Math.round(x.p)+' g';smartCarb.textContent=Math.round(x.c)+' g';smartFat.textContent=Math.round(x.f)+' g';if(typeof renderDayTargets==='function')renderDayTargets()};
const extendedPriceDefaults={rice:6.5,beans:9,milk:6,banana:.9,bread:9,oats:14,beef:40,pasta:8};
function restoreExtendedPrices(){priceRice.value=store.get('price.rice','6.5');priceBeans.value=store.get('price.beans','9');priceMilk.value=store.get('price.milk','6');priceBanana.value=store.get('price.banana','.9');priceBread.value=store.get('price.bread','9');priceOats.value=store.get('price.oats','14');priceBeef.value=store.get('price.beef','40');pricePasta.value=store.get('price.pasta','8')}
function saveExtendedPrices(){const map={rice:priceRice.value,beans:priceBeans.value,milk:priceMilk.value,banana:priceBanana.value,bread:priceBread.value,oats:priceOats.value,beef:priceBeef.value,pasta:pricePasta.value};Object.entries(map).forEach(([k,v])=>store.set('price.'+k,v));renderFoodCost()}
