// Exercise knowledge base
const exerciseLibrary={
 'seg-hip':{name:'Hip Thrust',group:'gluteos',muscles:['Glúteo máximo','Posterior como sinergista'],execution:'Apoie a parte alta das costas, mantenha queixo levemente recolhido e estenda o quadril até alinhar tronco e coxas. Termine contraindo glúteos, sem hiperestender a lombar.',errors:['Hiperestender a lombar','Pés muito longe ou muito perto','Perder controle na descida'],alts:['Glute bridge na máquina','Hip thrust no Smith']},
 'seg-leg':{name:'Leg Press 45°',group:'quadriceps',muscles:['Quadríceps','Glúteos'],execution:'Pés firmes na plataforma, joelhos acompanhando a linha dos pés e amplitude que permita manter quadril apoiado.',errors:['Descolar quadril do banco','Fechar os joelhos','Travar joelhos com impacto'],alts:['Hack squat','Agachamento no Smith']},
 'seg-bulg':{name:'Agachamento búlgaro',group:'gluteos',muscles:['Glúteos','Quadríceps'],execution:'Apoie o pé de trás e mantenha maior parte da carga na perna da frente. Desça controlando o joelho e empurre o chão.',errors:['Passo curto demais','Perder equilíbrio','Inclinar excessivamente'],alts:['Passada reversa','Step-up']},
 'seg-ext':{name:'Cadeira extensora',group:'quadriceps',muscles:['Quadríceps'],execution:'Ajuste o eixo da máquina ao joelho e estenda sem chutar. Controle totalmente a volta.',errors:['Usar impulso','Descolar quadril','Carga que reduz amplitude'],alts:['Sissy squat assistido','Leg press com foco em quadríceps']},
 'seg-abd':{name:'Cadeira abdutora',group:'gluteos',muscles:['Glúteo médio','Glúteo mínimo'],execution:'Abra os joelhos de forma controlada e mantenha tensão contínua. Evite bater as placas.',errors:['Usar balanço','Amplitude curta','Relaxar no retorno'],alts:['Abdução na polia','Caminhada lateral com miniband']},
 'seg-pant':{name:'Panturrilha',group:'quadriceps',muscles:['Gastrocnêmio','Sóleo'],execution:'Desça o calcanhar sob controle e suba até máxima flexão plantar sem quicar.',errors:['Repetições muito rápidas','Pouca amplitude','Usar impulso'],alts:['Panturrilha sentada','Panturrilha no leg press']},
 'qua-pux':{name:'Puxada frontal',group:'costas',muscles:['Latíssimo do dorso','Bíceps'],execution:'Inicie deprimindo as escápulas e puxe a barra em direção à parte alta do peito sem jogar o tronco para trás.',errors:['Puxar atrás da nuca','Balançar o tronco','Encolher ombros'],alts:['Puxada neutra','Barra assistida']},
 'qua-rem':{name:'Remada sentada',group:'costas',muscles:['Dorsais','Romboides','Trapézio médio'],execution:'Mantenha tronco estável e leve os cotovelos para trás, aproximando as escápulas.',errors:['Balançar o tronco','Encolher ombros','Soltar a carga rápido'],alts:['Remada máquina articulada','Remada com halteres']},
 'qua-des':{name:'Desenvolvimento de ombros',group:'ombros',muscles:['Deltoide anterior','Deltoide lateral','Tríceps'],execution:'Empurre a carga acima da cabeça mantendo costelas controladas e punhos alinhados.',errors:['Arquear lombar','Descer além do confortável','Carga excessiva'],alts:['Shoulder press máquina','Desenvolvimento com halteres']},
 'qua-lat':{name:'Elevação lateral',group:'ombros',muscles:['Deltoide lateral'],execution:'Eleve os braços no plano da escápula até próximo da linha dos ombros, sem encolher.',errors:['Dar impulso','Subir demais','Punhos muito rodados'],alts:['Elevação lateral na polia','Máquina lateral']},
 'qua-chest':{name:'Chest Press',group:'peito',muscles:['Peitoral','Tríceps','Deltoide anterior'],execution:'Ajuste o banco para as alças ficarem na linha do meio do peito e empurre mantendo escápulas estáveis.',errors:['Ombros projetados à frente','Carga que encurta amplitude','Punhos quebrados'],alts:['Supino com halteres','Supino máquina convergente']},
 'qua-bic':{name:'Rosca bíceps',group:'bracos',muscles:['Bíceps','Braquial'],execution:'Mantenha cotovelos próximos ao corpo e flexione sem balançar o tronco.',errors:['Roubar com lombar','Cotovelos viajando','Soltar a descida'],alts:['Rosca máquina','Rosca na polia']},
 'qua-tri':{name:'Tríceps na polia',group:'bracos',muscles:['Tríceps'],execution:'Cotovelos fixos ao lado do corpo; estenda completamente e retorne controlando.',errors:['Mover ombros','Abrir cotovelos','Usar o peso do corpo'],alts:['Tríceps máquina','Extensão unilateral na polia']},
 'sex-rdl':{name:'Levantamento romeno',group:'posterior',muscles:['Posterior de coxa','Glúteos'],execution:'Empurre o quadril para trás com joelhos levemente flexionados e coluna neutra até sentir alongamento dos posteriores.',errors:['Arredondar lombar','Agachar em vez de dobrar quadril','Afastar carga do corpo'],alts:['RDL no Smith','Stiff com halteres']},
 'sex-hip':{name:'Hip Thrust',group:'gluteos',muscles:['Glúteo máximo'],execution:'Mesma lógica do Hip Thrust de segunda; aqui o foco é controlar a fadiga e manter amplitude.',errors:['Hiperestender lombar','Perder apoio dos pés','Repetições incompletas'],alts:['Glute bridge máquina','Smith hip thrust']},
 'sex-flex':{name:'Mesa/cadeira flexora',group:'posterior',muscles:['Isquiotibiais'],execution:'Flexione o joelho sem tirar quadril do apoio e controle a volta.',errors:['Levantar quadril','Usar impulso','Carga excessiva'],alts:['Mesa flexora','Flexora em pé unilateral']},
 'sex-step':{name:'Step-up / passada reversa',group:'gluteos',muscles:['Glúteos','Quadríceps'],execution:'Suba usando a perna de apoio, evitando impulso excessivo da perna de trás.',errors:['Degrau alto demais','Empurrar com perna de trás','Joelho colapsando'],alts:['Búlgaro','Afundo no Smith']},
 'sex-abd':{name:'Cadeira abdutora',group:'gluteos',muscles:['Glúteo médio'],execution:'Controle abertura e retorno, mantendo tensão.',errors:['Balanço','Choque das placas','Amplitude curta'],alts:['Polia','Miniband lateral']},
 'sex-pant':{name:'Panturrilha sentada',group:'posterior',muscles:['Sóleo','Gastrocnêmio'],execution:'Use amplitude completa e pausa breve no alongamento.',errors:['Quicar','Pouca amplitude','Excesso de carga'],alts:['Panturrilha em pé','Leg press']},
 'dom-pux':{name:'Puxada neutra',group:'costas',muscles:['Latíssimo','Bíceps'],execution:'Puxe com cotovelos para baixo mantendo ombros longe das orelhas.',errors:['Balanço','Encolher ombros','Amplitude incompleta'],alts:['Puxada frontal','Barra assistida']},
 'dom-rem':{name:'Remada unilateral',group:'costas',muscles:['Dorsais','Romboides'],execution:'Mantenha tronco estável e puxe o cotovelo em direção ao quadril.',errors:['Rodar tronco','Encolher ombro','Usar impulso'],alts:['Remada articulada unilateral','Remada baixa unilateral']},
 'dom-chest':{name:'Chest Press',group:'peito',muscles:['Peitoral','Tríceps'],execution:'Controle a fase de retorno e mantenha escápulas apoiadas.',errors:['Perder posição dos ombros','Travar cotovelos com impacto','Carga excessiva'],alts:['Supino halteres','Peck deck como complemento']},
 'dom-des':{name:'Desenvolvimento',group:'ombros',muscles:['Deltoides','Tríceps'],execution:'Empurre acima da cabeça sem compensar com lombar.',errors:['Arquear lombar','Carga excessiva','Amplitude desconfortável'],alts:['Máquina','Halteres']},
 'dom-lat':{name:'Elevação lateral',group:'ombros',muscles:['Deltoide lateral'],execution:'Suba controlado e mantenha tensão no deltoide.',errors:['Impulso','Encolher trapézio','Carga alta demais'],alts:['Polia','Máquina']},
 'dom-post':{name:'Crucifixo invertido',group:'ombros',muscles:['Deltoide posterior','Romboides'],execution:'Abra os braços mantendo peito apoiado ou tronco firme, focando parte posterior dos ombros.',errors:['Encolher ombros','Usar lombar','Jogar a carga'],alts:['Peck deck invertido','Face pull']},
 'dom-arm':{name:'Bíceps + tríceps',group:'bracos',muscles:['Bíceps','Tríceps'],execution:'Escolha um exercício confortável para cada e execute com cotovelos estáveis.',errors:['Carga excessiva','Impulso','Amplitude curta'],alts:['Polia','Máquinas de braço']}
};
function muscleSvg(group){const h={gluteos:'#b8ff4f',quadriceps:'#b8ff4f',posterior:'#6ce5ff',costas:'#6ce5ff',ombros:'#ffd166',peito:'#ff9fbd',bracos:'#ffd166'}[group]||'#6ce5ff';return `<svg viewBox="0 0 100 180"><circle cx="50" cy="18" r="12" fill="#303946"/><rect x="39" y="31" width="22" height="48" rx="10" fill="#303946"/><rect x="23" y="37" width="14" height="48" rx="7" fill="${['ombros','bracos'].includes(group)?h:'#303946'}"/><rect x="63" y="37" width="14" height="48" rx="7" fill="${['ombros','bracos'].includes(group)?h:'#303946'}"/><rect x="37" y="75" width="12" height="70" rx="6" fill="${['quadriceps','posterior'].includes(group)?h:'#303946'}"/><rect x="51" y="75" width="12" height="70" rx="6" fill="${['quadriceps','posterior'].includes(group)?h:'#303946'}"/><ellipse cx="50" cy="70" rx="17" ry="11" fill="${group==='gluteos'?h:'#303946'}"/><path d="M39 33 Q50 27 61 33 L60 57 Q50 64 40 57Z" fill="${['costas','peito'].includes(group)?h:'#303946'}"/></svg>`}
function renderExerciseLibrary(){const q=(exerciseSearch.value||'').toLowerCase(),g=muscleFilter.value;const items=Object.entries(exerciseLibrary).filter(([k,x])=>(!g||x.group===g)&&(!q||x.name.toLowerCase().includes(q)||x.muscles.join(' ').toLowerCase().includes(q)));exerciseLibraryGrid.innerHTML=items.length?items.map(([k,x])=>`<div class="library-item"><div class="muscle-visual">${muscleSvg(x.group)}</div><div><b>${x.name}</b><p>${x.execution.slice(0,120)}${x.execution.length>120?'…':''}</p><div class="lib-tags">${x.muscles.map(m=>`<span>${m}</span>`).join('')}</div><button onclick="openExerciseModal('${k}')">Ver execução e alternativas</button></div></div>`).join(''):'<div class="empty-state">Nenhum exercício encontrado.</div>'}
function openExerciseModal(key){const x=exerciseLibrary[key];if(!x)return;exerciseModalTitle.textContent=x.name;exerciseModalContent.innerHTML=`<div class="exercise-detail-grid"><div class="exercise-big-visual">${muscleSvg(x.group)}</div><div class="exercise-info"><h4>Músculos principais</h4><p>${x.muscles.join(' • ')}</p><h4>Execução</h4><p>${x.execution}</p><h4>Erros que mais atrapalham</h4><ul>${x.errors.map(e=>`<li>${e}</li>`).join('')}</ul><h4>Alternativas equivalentes</h4><div class="alt-grid">${x.alts.map(a=>`<div>${a}</div>`).join('')}</div></div></div>`;exerciseModal.classList.add('open')}
function closeExerciseModal(){exerciseModal.classList.remove('open')}
function exerciseRIR(key){return store.get(dk('rir.'+key),'')}
function setExerciseRIR(key,v){store.set(dk('rir.'+key),v);const row=document.querySelector(`.exercise[data-ex="${key}"]`);if(row)updateExerciseStatus(row)}
function suggestedNextLoad(key){const hist=setHistory(key).filter(r=>r.date<=isoDate(selectedDate)).sort((a,b)=>a.date.localeCompare(b.date));if(!hist.length)return null;const last=hist[hist.length-1],loads=(last.sets||[]).map(s=>num(s.load)).filter(v=>v!=null),reps=(last.sets||[]).map(s=>num(s.reps)).filter(v=>v!=null);if(!loads.length||!reps.length)return null;const row=document.querySelector(`.exercise[data-ex="${key}"]`),p=row?parsePrescription(row.dataset.range):{max:12};const rir=num(exerciseRIR(key)),best=Math.max(...loads);if(reps.every(r=>r>=p.max)&&(rir==null||rir<=2))return Math.round(best*1.035*2)/2;return best}
function performanceDrop(key){const hist=setHistory(key).filter(r=>r.date<isoDate(selectedDate)).sort((a,b)=>a.date.localeCompare(b.date)).slice(-3);if(hist.length<3)return false;const vols=hist.map(r=>(r.sets||[]).reduce((a,s)=>a+(num(s.load)||0)*(num(s.reps)||0),0));return vols[2]<vols[1]*.9&&vols[1]<vols[0]*.95}
