function avgWeight7Days(){const arr=measurements().filter(x=>x.weight!=null).slice(-7);if(!arr.length)return null;return arr.reduce((a,x)=>a+x.weight,0)/arr.length}
function readinessFromCheckin(){const c=getCheckin(currentCheckinWeek());if(!c)return null;const sleep=num(c.sleep),energy=num(c.energy),recovery=num(c.recovery),mot=num(c.motivation),sore=num(c.soreness),vals=[sleep,energy,recovery,mot].filter(v=>v!=null);if(!vals.length)return null;let score=vals.reduce((a,v)=>a+v,0)/vals.length/5*100;if(sore!=null)score-=Math.max(0,sore-3)*6;return Math.max(0,Math.min(100,Math.round(score)))}
function transformScore(){const arr=measurements(),s=weekSummaryData();if(!arr.length)return 0;const first=arr[0],last=arr[arr.length-1];let body=50;if(first.waist!=null&&last.waist!=null)body+=Math.max(-15,Math.min(15,(first.waist-last.waist)*4));if(first.hip!=null&&last.hip!=null)body+=Math.max(-10,Math.min(10,(last.hip-first.hip)*3));if(first.thigh!=null&&last.thigh!=null)body+=Math.max(-10,Math.min(10,(last.thigh-first.thigh)*3));const train=s.trainDays.length?s.trainDone/s.trainDays.length*100:0,consistency=(train+s.nutrition+s.water)/3;return Math.max(0,Math.min(100,Math.round(body*.55+consistency*.45)))}
function renderAdvancedBody(){const avg=avgWeight7Days(),arr=measurements(),last=arr[arr.length-1],prev=arr.length>1?arr[arr.length-2]:null;avgWeight7.textContent=avg!=null?avg.toFixed(1).replace('.',',')+' kg':'—';avgWeight7Delta.textContent=avg!=null&&prev?.weight!=null?`último registro ${last.weight?.toFixed?.(1)?.replace('.',',')||last.weight} kg`:'aguardando registros';waistHipRatio.textContent=(last?.waist!=null&&last?.hip!=null)?(last.waist/last.hip).toFixed(2).replace('.',','):'—';const r=readinessFromCheckin();readinessScore.textContent=r!=null?r+'%':'—';readinessLabel.textContent=r==null?'check-in semanal':r>=80?'recuperação alta':r>=60?'recuperação moderada':'priorizar recuperação';transformationScore.textContent=transformScore()}
function saveWeeklyCheckinV3(){const w=currentCheckinWeek(),c={week:w,date:isoDate(selectedDate),weight:num(ciWeight.value),waist:num(ciWaist.value),hip:num(ciHip.value),thigh:num(ciThigh.value),sleep:num(ciSleep.value),hunger:num(ciHunger.value),energy:num(ciEnergy.value),recovery:num(ciRecovery.value),soreness:num(ciSoreness.value),motivation:num(ciMotivation.value),note:ciNote.value.trim()};store.set(checkinKey(w),c);if(c.weight!=null||c.waist!=null||c.hip!=null||c.thigh!=null){let arr=measurements().filter(x=>x.date!==c.date);arr.push({date:c.date,weight:c.weight,waist:c.waist,hip:c.hip,thigh:c.thigh,note:'Check-in semanal'});arr.sort((a,b)=>a.date.localeCompare(b.date));store.set('measurements',arr)}loadCurrentCheckin();renderMeasurements();renderProgressDashboard();renderAdvancedBody();toast('Check-in salvo')}
const originalSaveWeeklyCheckin=saveWeeklyCheckin;saveWeeklyCheckin=saveWeeklyCheckinV3;
const originalLoadCurrentCheckin=loadCurrentCheckin;loadCurrentCheckin=function(){originalLoadCurrentCheckin();const c=getCheckin(currentCheckinWeek())||{};ciSoreness.value=c.soreness??'';ciMotivation.value=c.motivation??'';renderCheckinDecision(c);renderAdvancedBody()};
const originalRenderCheckinDecision=renderCheckinDecision;renderCheckinDecision=function(c){if(!c||Object.keys(c).length===0){originalRenderCheckinDecision(c);return}originalRenderCheckinDecision(c);const ready=readinessFromCheckin();if(ready!=null&&ready<55){checkinDecision.textContent='Priorizar recuperação';checkinDecisionDetail.textContent='Readiness baixo. Evite aumentar volume/cardio e reavalie sono, dor muscular e recuperação.'}};
function monthBounds(d){const start=new Date(d.getFullYear(),d.getMonth(),1,12),end=new Date(d.getFullYear(),d.getMonth()+1,0,12);return {start,end}}
function monthlySummaryData(){const {start,end}=monthBounds(selectedDate),today=new Date();today.setHours(12,0,0,0);const cutoff=end<today?end:today,days=cutoff>=start?datesBetween(start,cutoff):[],train=days.filter(d=>isMuscleDay(d.getDay())),td=train.filter(trainingCompletedForDate).length,cardio=days.filter(d=>isCardioPlanned(d.getDay())),cd=cardio.filter(cardioCompletedForDate).length,tracked=days.filter(dayHasAnyTracking),nut=tracked.length?Math.round(tracked.reduce((a,d)=>a+nutritionPctForDate(d),0)/tracked.length):0,wat=tracked.length?Math.round(tracked.reduce((a,d)=>a+Math.min(100,Math.round(dateStoreGet(isoDate(d),'water',0)/dowPlans[d.getDay()].water*100)),0)/tracked.length):0;return {start,end,days,train,td,cardio,cd,tracked,nut,wat}}
function monthlyText(){const s=monthlySummaryData(),arr=measurements().filter(x=>parseISO(x.date)>=s.start&&parseISO(x.date)<=s.end),first=arr[0],last=arr[arr.length-1];return `FORJA MUSCLE • ${s.start.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}\nTreinos: ${s.td}/${s.train.length}\nCardio: ${s.cd}/${s.cardio.length}\nNutrição: ${s.nut}%\nÁgua: ${s.wat}%\nPeso: ${first?.weight??'—'} → ${last?.weight??'—'} kg\nCintura: ${first?.waist??'—'} → ${last?.waist??'—'} cm\nScore de evolução: ${transformScore()}/100`}
function openMonthlyReport(){const s=monthlySummaryData(),arr=measurements().filter(x=>parseISO(x.date)>=s.start&&parseISO(x.date)<=s.end),first=arr[0],last=arr[arr.length-1];monthlyReportTitle.textContent=s.start.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});monthlyReportContent.innerHTML=`<div class="report-hero"><span>VISÃO DO MÊS</span><b>${transformScore()}/100</b><span>score atual de evolução</span></div><div class="report-grid"><div><span>TREINOS</span><b>${s.td}/${s.train.length}</b></div><div><span>CARDIO</span><b>${s.cd}/${s.cardio.length}</b></div><div><span>NUTRIÇÃO</span><b>${s.nut}%</b></div><div><span>ÁGUA</span><b>${s.wat}%</b></div></div><div class="report-section"><h4>Medidas no mês</h4><p>Peso: ${first?.weight??'—'} → ${last?.weight??'—'} kg • Cintura: ${first?.waist??'—'} → ${last?.waist??'—'} cm • Quadril: ${first?.hip??'—'} → ${last?.hip??'—'} cm • Coxa: ${first?.thigh??'—'} → ${last?.thigh??'—'} cm</p></div>`;monthlyReportModal.classList.add('open')}
function closeMonthlyReport(){monthlyReportModal.classList.remove('open')}
function printMonthlyReport(){const content=monthlyReportContent.innerHTML,win=window.open('','_blank');if(!win){toast('Permita pop-ups');return}win.document.write(`<html><head><title>FORJA MUSCLE</title></head><body><h1>FORJA MUSCLE</h1><h2>${monthlyReportTitle.textContent}</h2>${content}</body></html>`);win.document.close();setTimeout(()=>win.print(),300)}
async function copyMonthlyReport(){try{await navigator.clipboard.writeText(monthlyText());toast('Resumo mensal copiado')}catch(e){toast('Não foi possível copiar')}}
function csvDownload(name,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(';')).join('\n'),blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportMeasurementsCSV(){csvDownload(`forja-medidas-${isoDate(new Date())}.csv`,[['Data','Peso kg','Cintura cm','Quadril cm','Coxa cm','Observação'],...measurements().map(x=>[x.date,x.weight,x.waist,x.hip,x.thigh,x.note])]);toast('CSV de medidas exportado')}
function exportTrainingCSV(){const rows=[['Exercício','Data','Série','Carga kg','Repetições','Concluída']];Object.keys(exerciseLibrary).forEach(k=>setHistory(k).forEach(h=>(h.sets||[]).forEach((s,i)=>rows.push([exerciseLibrary[k]?.name||k,h.date,i+1,s.load,s.reps,s.done?'Sim':'Não']))));csvDownload(`forja-treinos-${isoDate(new Date())}.csv`,rows);toast('CSV de treinos exportado')}
function registerServiceWorker(){if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
function renderAll(){renderPhase();renderCardio();renderToday();renderWater();notesRender();renderMeasurements();buildSetCards();renderProgress();renderTodayWorkoutCard();renderRest();renderProgressDashboard();restoreFoodPrices();restoreExtendedPrices();renderMealChoices();renderCustomFoods();renderDayTargets();renderHomeToday();loadCurrentCheckin();renderProjectCompletion();renderWeeklySummary();renderExerciseLibrary();renderAdvancedBody()}
const savedTab=store.get('ui.tab','nutricao');const btn=document.querySelector(`[data-tab="${savedTab}"]`);if(btn&&savedTab!=='nutricao')btn.click();if(store.get('ui.pdCollapsed',false)){progressDashboard.classList.add('collapsed');pdToggle.textContent='Mostrar painel'}renderAll();registerServiceWorker();
